# Generated by Django 4.1.5 on 2023-05-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Emp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Ename", models.CharField(max_length=50)),
                ("Email", models.EmailField(max_length=54)),
                ("Mobile_no", models.IntegerField()),
                ("Address", models.TextField()),
                ("Joining_date", models.DateField()),
            ],
        ),
    ]
